/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.9 2005/01/07 09:37:18 dts12 Exp $
 */
#ifndef RMON_H
#define RMON_H

/* function declarations */
void init_rmon(void);
Netsnmp_Node_Handler handle_protocolDirLastChange;
Netsnmp_Node_Handler handle_addressMapInserts;
Netsnmp_Node_Handler handle_addressMapDeletes;
Netsnmp_Node_Handler handle_addressMapMaxDesiredEntries;
Netsnmp_Node_Handler handle_probeCapabilities;
Netsnmp_Node_Handler handle_probeSoftwareRev;
Netsnmp_Node_Handler handle_probeHardwareRev;
Netsnmp_Node_Handler handle_probeDateTime;
Netsnmp_Node_Handler handle_probeResetControl;
Netsnmp_Node_Handler handle_probeDownloadFile;
Netsnmp_Node_Handler handle_probeDownloadTFTPServer;
Netsnmp_Node_Handler handle_probeDownloadAction;
Netsnmp_Node_Handler handle_probeDownloadStatus;
Netsnmp_Node_Handler handle_netDefaultGateway;
Netsnmp_Node_Handler handle_smonCapabilities;
Netsnmp_Node_Handler handle_hcRMONCapabilities;
Netsnmp_Node_Handler handle_hcAlarmCapabilities;

#endif /* RMON_H */
