/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.container.conf,v 1.8 2006/07/26 15:58:26 dts12 Exp $
 */
#ifndef RMONTABLE_H
#define RMONTABLE_H

/* TW Functions */
void ResetRmonTable(void);
void UpdateRmonDrop(int nDrop);
void UpdateRmonFlow(struct tw_flow *pFlow,int nLen);
void UpdateRmonEth(struct tw_eth *pEth,int nLen);
void UpdateRmonIP(struct tw_eth *pEth,struct tw_ip *pIP,int nLen);
void SetDataSource(char *szDev);
void LoadTwRmonConf(void);
void SaveTwRmonConf(void);

/* function declarations */
void init_rmonTable(void);
void initialize_table_etherStatsTable(void);
Netsnmp_Node_Handler etherStatsTable_handler;
void initialize_table_etherStats2Table(void);
Netsnmp_Node_Handler etherStats2Table_handler;
void initialize_table_etherStatsHighCapacityTable(void);
Netsnmp_Node_Handler etherStatsHighCapacityTable_handler;
void initialize_table_historyControlTable(void);
Netsnmp_Node_Handler historyControlTable_handler;
void initialize_table_etherHistoryTable(void);
Netsnmp_Node_Handler etherHistoryTable_handler;
void initialize_table_historyControl2Table(void);
Netsnmp_Node_Handler historyControl2Table_handler;
void initialize_table_etherHistoryHighCapacityTable(void);
Netsnmp_Node_Handler etherHistoryHighCapacityTable_handler;
void initialize_table_alarmTable(void);
Netsnmp_Node_Handler alarmTable_handler;
void initialize_table_hostControlTable(void);
Netsnmp_Node_Handler hostControlTable_handler;
void initialize_table_hostTable(void);
Netsnmp_Node_Handler hostTable_handler;
void initialize_table_hostTimeTable(void);
Netsnmp_Node_Handler hostTimeTable_handler;
void initialize_table_hostControl2Table(void);
Netsnmp_Node_Handler hostControl2Table_handler;
void initialize_table_matrixControlTable(void);
Netsnmp_Node_Handler matrixControlTable_handler;
void initialize_table_matrixSDTable(void);
Netsnmp_Node_Handler matrixSDTable_handler;
void initialize_table_matrixDSTable(void);
Netsnmp_Node_Handler matrixDSTable_handler;
void initialize_table_matrixControl2Table(void);
Netsnmp_Node_Handler matrixControl2Table_handler;
void initialize_table_eventTable(void);
Netsnmp_Node_Handler eventTable_handler;
void initialize_table_logTable(void);
Netsnmp_Node_Handler logTable_handler;
void initialize_table_protocolDirTable(void);
Netsnmp_Node_Handler protocolDirTable_handler;
void initialize_table_protocolDistControlTable(void);
Netsnmp_Node_Handler protocolDistControlTable_handler;
void initialize_table_protocolDistStatsTable(void);
Netsnmp_Node_Handler protocolDistStatsTable_handler;
void initialize_table_addressMapControlTable(void);
Netsnmp_Node_Handler addressMapControlTable_handler;
void initialize_table_addressMapTable(void);
Netsnmp_Node_Handler addressMapTable_handler;
void initialize_table_hlHostControlTable(void);
Netsnmp_Node_Handler hlHostControlTable_handler;
void initialize_table_nlHostTable(void);
Netsnmp_Node_Handler nlHostTable_handler;
void initialize_table_hlMatrixControlTable(void);
Netsnmp_Node_Handler hlMatrixControlTable_handler;
void initialize_table_nlMatrixSDTable(void);
Netsnmp_Node_Handler nlMatrixSDTable_handler;
void initialize_table_nlMatrixDSTable(void);
Netsnmp_Node_Handler nlMatrixDSTable_handler;
void initialize_table_alHostTable(void);
Netsnmp_Node_Handler alHostTable_handler;
void initialize_table_alMatrixSDTable(void);
Netsnmp_Node_Handler alMatrixSDTable_handler;
void initialize_table_alMatrixDSTable(void);
Netsnmp_Node_Handler alMatrixDSTable_handler;

/* column number definitions for table etherStatsTable */
       #define COLUMN_ETHERSTATSINDEX		1
       #define COLUMN_ETHERSTATSDATASOURCE		2
       #define COLUMN_ETHERSTATSDROPEVENTS		3
       #define COLUMN_ETHERSTATSOCTETS		4
       #define COLUMN_ETHERSTATSPKTS		5
       #define COLUMN_ETHERSTATSBROADCASTPKTS		6
       #define COLUMN_ETHERSTATSMULTICASTPKTS		7
       #define COLUMN_ETHERSTATSCRCALIGNERRORS		8
       #define COLUMN_ETHERSTATSUNDERSIZEPKTS		9
       #define COLUMN_ETHERSTATSOVERSIZEPKTS		10
       #define COLUMN_ETHERSTATSFRAGMENTS		11
       #define COLUMN_ETHERSTATSJABBERS		12
       #define COLUMN_ETHERSTATSCOLLISIONS		13
       #define COLUMN_ETHERSTATSPKTS64OCTETS		14
       #define COLUMN_ETHERSTATSPKTS65TO127OCTETS		15
       #define COLUMN_ETHERSTATSPKTS128TO255OCTETS		16
       #define COLUMN_ETHERSTATSPKTS256TO511OCTETS		17
       #define COLUMN_ETHERSTATSPKTS512TO1023OCTETS		18
       #define COLUMN_ETHERSTATSPKTS1024TO1518OCTETS		19
       #define COLUMN_ETHERSTATSOWNER		20
       #define COLUMN_ETHERSTATSSTATUS		21


/* column number definitions for table etherStats2Table */
       #define COLUMN_ETHERSTATSDROPPEDFRAMES		1
       #define COLUMN_ETHERSTATSCREATETIME		2


/* column number definitions for table etherStatsHighCapacityTable */
       #define COLUMN_ETHERSTATSHIGHCAPACITYOVERFLOWPKTS		1
       #define COLUMN_ETHERSTATSHIGHCAPACITYPKTS		2
       #define COLUMN_ETHERSTATSHIGHCAPACITYOVERFLOWOCTETS		3
       #define COLUMN_ETHERSTATSHIGHCAPACITYOCTETS		4
       #define COLUMN_ETHERSTATSHIGHCAPACITYOVERFLOWPKTS64OCTETS		5
       #define COLUMN_ETHERSTATSHIGHCAPACITYPKTS64OCTETS		6
       #define COLUMN_ETHERSTATSHIGHCAPACITYOVERFLOWPKTS65TO127OCTETS		7
       #define COLUMN_ETHERSTATSHIGHCAPACITYPKTS65TO127OCTETS		8
       #define COLUMN_ETHERSTATSHIGHCAPACITYOVERFLOWPKTS128TO255OCTETS		9
       #define COLUMN_ETHERSTATSHIGHCAPACITYPKTS128TO255OCTETS		10
       #define COLUMN_ETHERSTATSHIGHCAPACITYOVERFLOWPKTS256TO511OCTETS		11
       #define COLUMN_ETHERSTATSHIGHCAPACITYPKTS256TO511OCTETS		12
       #define COLUMN_ETHERSTATSHIGHCAPACITYOVERFLOWPKTS512TO1023OCTETS		13
       #define COLUMN_ETHERSTATSHIGHCAPACITYPKTS512TO1023OCTETS		14
       #define COLUMN_ETHERSTATSHIGHCAPACITYOVERFLOWPKTS1024TO1518OCTETS		15
       #define COLUMN_ETHERSTATSHIGHCAPACITYPKTS1024TO1518OCTETS		16

/* column number definitions for table historyControlTable */
       #define COLUMN_HISTORYCONTROLINDEX		1
       #define COLUMN_HISTORYCONTROLDATASOURCE		2
       #define COLUMN_HISTORYCONTROLBUCKETSREQUESTED		3
       #define COLUMN_HISTORYCONTROLBUCKETSGRANTED		4
       #define COLUMN_HISTORYCONTROLINTERVAL		5
       #define COLUMN_HISTORYCONTROLOWNER		6
       #define COLUMN_HISTORYCONTROLSTATUS		7

/* column number definitions for table etherHistoryTable */
       #define COLUMN_ETHERHISTORYINDEX		1
       #define COLUMN_ETHERHISTORYSAMPLEINDEX		2
       #define COLUMN_ETHERHISTORYINTERVALSTART		3
       #define COLUMN_ETHERHISTORYDROPEVENTS		4
       #define COLUMN_ETHERHISTORYOCTETS		5
       #define COLUMN_ETHERHISTORYPKTS		6
       #define COLUMN_ETHERHISTORYBROADCASTPKTS		7
       #define COLUMN_ETHERHISTORYMULTICASTPKTS		8
       #define COLUMN_ETHERHISTORYCRCALIGNERRORS		9
       #define COLUMN_ETHERHISTORYUNDERSIZEPKTS		10
       #define COLUMN_ETHERHISTORYOVERSIZEPKTS		11
       #define COLUMN_ETHERHISTORYFRAGMENTS		12
       #define COLUMN_ETHERHISTORYJABBERS		13
       #define COLUMN_ETHERHISTORYCOLLISIONS		14
       #define COLUMN_ETHERHISTORYUTILIZATION		15

/* column number definitions for table historyControl2Table */
       #define COLUMN_HISTORYCONTROLDROPPEDFRAMES		1

/* column number definitions for table etherHistoryHighCapacityTable */
       #define COLUMN_ETHERHISTORYHIGHCAPACITYOVERFLOWPKTS		1
       #define COLUMN_ETHERHISTORYHIGHCAPACITYPKTS		2
       #define COLUMN_ETHERHISTORYHIGHCAPACITYOVERFLOWOCTETS		3
       #define COLUMN_ETHERHISTORYHIGHCAPACITYOCTETS		4

/* column number definitions for table alarmTable */
       #define COLUMN_ALARMINDEX		1
       #define COLUMN_ALARMINTERVAL		2
       #define COLUMN_ALARMVARIABLE		3
       #define COLUMN_ALARMSAMPLETYPE		4
       #define COLUMN_ALARMVALUE		5
       #define COLUMN_ALARMSTARTUPALARM		6
       #define COLUMN_ALARMRISINGTHRESHOLD		7
       #define COLUMN_ALARMFALLINGTHRESHOLD		8
       #define COLUMN_ALARMRISINGEVENTINDEX		9
       #define COLUMN_ALARMFALLINGEVENTINDEX		10
       #define COLUMN_ALARMOWNER		11
       #define COLUMN_ALARMSTATUS		12

/* column number definitions for table hostControlTable */
       #define COLUMN_HOSTCONTROLINDEX		1
       #define COLUMN_HOSTCONTROLDATASOURCE		2
       #define COLUMN_HOSTCONTROLTABLESIZE		3
       #define COLUMN_HOSTCONTROLLASTDELETETIME		4
       #define COLUMN_HOSTCONTROLOWNER		5
       #define COLUMN_HOSTCONTROLSTATUS		6

/* column number definitions for table hostTable */
       #define COLUMN_HOSTADDRESS		1
       #define COLUMN_HOSTCREATIONORDER		2
       #define COLUMN_HOSTINDEX		3
       #define COLUMN_HOSTINPKTS		4
       #define COLUMN_HOSTOUTPKTS		5
       #define COLUMN_HOSTINOCTETS		6
       #define COLUMN_HOSTOUTOCTETS		7
       #define COLUMN_HOSTOUTERRORS		8
       #define COLUMN_HOSTOUTBROADCASTPKTS		9
       #define COLUMN_HOSTOUTMULTICASTPKTS		10

/* column number definitions for table hostTimeTable */
       #define COLUMN_HOSTTIMEADDRESS		1
       #define COLUMN_HOSTTIMECREATIONORDER		2
       #define COLUMN_HOSTTIMEINDEX		3
       #define COLUMN_HOSTTIMEINPKTS		4
       #define COLUMN_HOSTTIMEOUTPKTS		5
       #define COLUMN_HOSTTIMEINOCTETS		6
       #define COLUMN_HOSTTIMEOUTOCTETS		7
       #define COLUMN_HOSTTIMEOUTERRORS		8
       #define COLUMN_HOSTTIMEOUTBROADCASTPKTS		9
       #define COLUMN_HOSTTIMEOUTMULTICASTPKTS		10

/* column number definitions for table hostControl2Table */
       #define COLUMN_HOSTCONTROLDROPPEDFRAMES		1
       #define COLUMN_HOSTCONTROLCREATETIME		2

/* column number definitions for table matrixControlTable */
       #define COLUMN_MATRIXCONTROLINDEX		1
       #define COLUMN_MATRIXCONTROLDATASOURCE		2
       #define COLUMN_MATRIXCONTROLTABLESIZE		3
       #define COLUMN_MATRIXCONTROLLASTDELETETIME		4
       #define COLUMN_MATRIXCONTROLOWNER		5
       #define COLUMN_MATRIXCONTROLSTATUS		6

/* column number definitions for table matrixSDTable */
       #define COLUMN_MATRIXSDSOURCEADDRESS		1
       #define COLUMN_MATRIXSDDESTADDRESS		2
       #define COLUMN_MATRIXSDINDEX		3
       #define COLUMN_MATRIXSDPKTS		4
       #define COLUMN_MATRIXSDOCTETS		5
       #define COLUMN_MATRIXSDERRORS		6

/* column number definitions for table matrixDSTable */
       #define COLUMN_MATRIXDSSOURCEADDRESS		1
       #define COLUMN_MATRIXDSDESTADDRESS		2
       #define COLUMN_MATRIXDSINDEX		3
       #define COLUMN_MATRIXDSPKTS		4
       #define COLUMN_MATRIXDSOCTETS		5
       #define COLUMN_MATRIXDSERRORS		6

/* column number definitions for table matrixControl2Table */
       #define COLUMN_MATRIXCONTROLDROPPEDFRAMES		1
       #define COLUMN_MATRIXCONTROLCREATETIME		2

/* column number definitions for table eventTable */
       #define COLUMN_EVENTINDEX		1
       #define COLUMN_EVENTDESCRIPTION		2
       #define COLUMN_EVENTTYPE		3
       #define COLUMN_EVENTCOMMUNITY		4
       #define COLUMN_EVENTLASTTIMESENT		5
       #define COLUMN_EVENTOWNER		6
       #define COLUMN_EVENTSTATUS		7

/* column number definitions for table logTable */
       #define COLUMN_LOGEVENTINDEX		1
       #define COLUMN_LOGINDEX		2
       #define COLUMN_LOGTIME		3
       #define COLUMN_LOGDESCRIPTION		4


/* column number definitions for table protocolDirTable */
       #define COLUMN_PROTOCOLDIRID		1
       #define COLUMN_PROTOCOLDIRPARAMETERS		2
       #define COLUMN_PROTOCOLDIRLOCALINDEX		3
       #define COLUMN_PROTOCOLDIRDESCR		4
       #define COLUMN_PROTOCOLDIRTYPE		5
       #define COLUMN_PROTOCOLDIRADDRESSMAPCONFIG		6
       #define COLUMN_PROTOCOLDIRHOSTCONFIG		7
       #define COLUMN_PROTOCOLDIRMATRIXCONFIG		8
       #define COLUMN_PROTOCOLDIROWNER		9
       #define COLUMN_PROTOCOLDIRSTATUS		10

/* column number definitions for table protocolDistControlTable */
       #define COLUMN_PROTOCOLDISTCONTROLINDEX		1
       #define COLUMN_PROTOCOLDISTCONTROLDATASOURCE		2
       #define COLUMN_PROTOCOLDISTCONTROLDROPPEDFRAMES		3
       #define COLUMN_PROTOCOLDISTCONTROLCREATETIME		4
       #define COLUMN_PROTOCOLDISTCONTROLOWNER		5
       #define COLUMN_PROTOCOLDISTCONTROLSTATUS		6

/* column number definitions for table protocolDistStatsTable */
       #define COLUMN_PROTOCOLDISTSTATSPKTS		1
       #define COLUMN_PROTOCOLDISTSTATSOCTETS		2


/* column number definitions for table addressMapControlTable */
       #define COLUMN_ADDRESSMAPCONTROLINDEX		1
       #define COLUMN_ADDRESSMAPCONTROLDATASOURCE		2
       #define COLUMN_ADDRESSMAPCONTROLDROPPEDFRAMES		3
       #define COLUMN_ADDRESSMAPCONTROLOWNER		4
       #define COLUMN_ADDRESSMAPCONTROLSTATUS		5

/* column number definitions for table addressMapTable */
       #define COLUMN_ADDRESSMAPTIMEMARK		1
       #define COLUMN_ADDRESSMAPNETWORKADDRESS		2
       #define COLUMN_ADDRESSMAPSOURCE		3
       #define COLUMN_ADDRESSMAPPHYSICALADDRESS		4
       #define COLUMN_ADDRESSMAPLASTCHANGE		5

/* column number definitions for table hlHostControlTable */
       #define COLUMN_HLHOSTCONTROLINDEX		1
       #define COLUMN_HLHOSTCONTROLDATASOURCE		2
       #define COLUMN_HLHOSTCONTROLNLDROPPEDFRAMES		3
       #define COLUMN_HLHOSTCONTROLNLINSERTS		4
       #define COLUMN_HLHOSTCONTROLNLDELETES		5
       #define COLUMN_HLHOSTCONTROLNLMAXDESIREDENTRIES		6
       #define COLUMN_HLHOSTCONTROLALDROPPEDFRAMES		7
       #define COLUMN_HLHOSTCONTROLALINSERTS		8
       #define COLUMN_HLHOSTCONTROLALDELETES		9
       #define COLUMN_HLHOSTCONTROLALMAXDESIREDENTRIES		10
       #define COLUMN_HLHOSTCONTROLOWNER		11
       #define COLUMN_HLHOSTCONTROLSTATUS		12

/* column number definitions for table nlHostTable */
       #define COLUMN_NLHOSTTIMEMARK		1
       #define COLUMN_NLHOSTADDRESS		2
       #define COLUMN_NLHOSTINPKTS		3
       #define COLUMN_NLHOSTOUTPKTS		4
       #define COLUMN_NLHOSTINOCTETS		5
       #define COLUMN_NLHOSTOUTOCTETS		6
       #define COLUMN_NLHOSTOUTMACNONUNICASTPKTS		7
       #define COLUMN_NLHOSTCREATETIME		8

/* column number definitions for table hlMatrixControlTable */
       #define COLUMN_HLMATRIXCONTROLINDEX		1
       #define COLUMN_HLMATRIXCONTROLDATASOURCE		2
       #define COLUMN_HLMATRIXCONTROLNLDROPPEDFRAMES		3
       #define COLUMN_HLMATRIXCONTROLNLINSERTS		4
       #define COLUMN_HLMATRIXCONTROLNLDELETES		5
       #define COLUMN_HLMATRIXCONTROLNLMAXDESIREDENTRIES		6
       #define COLUMN_HLMATRIXCONTROLALDROPPEDFRAMES		7
       #define COLUMN_HLMATRIXCONTROLALINSERTS		8
       #define COLUMN_HLMATRIXCONTROLALDELETES		9
       #define COLUMN_HLMATRIXCONTROLALMAXDESIREDENTRIES		10
       #define COLUMN_HLMATRIXCONTROLOWNER		11
       #define COLUMN_HLMATRIXCONTROLSTATUS		12

/* column number definitions for table nlMatrixSDTable */
       #define COLUMN_NLMATRIXSDTIMEMARK		1
       #define COLUMN_NLMATRIXSDSOURCEADDRESS		2
       #define COLUMN_NLMATRIXSDDESTADDRESS		3
       #define COLUMN_NLMATRIXSDPKTS		4
       #define COLUMN_NLMATRIXSDOCTETS		5
       #define COLUMN_NLMATRIXSDCREATETIME		6

/* column number definitions for table nlMatrixDSTable */
       #define COLUMN_NLMATRIXDSTIMEMARK		1
       #define COLUMN_NLMATRIXDSSOURCEADDRESS		2
       #define COLUMN_NLMATRIXDSDESTADDRESS		3
       #define COLUMN_NLMATRIXDSPKTS		4
       #define COLUMN_NLMATRIXDSOCTETS		5
       #define COLUMN_NLMATRIXDSCREATETIME		6

/* column number definitions for table alHostTable */
       #define COLUMN_ALHOSTTIMEMARK		1
       #define COLUMN_ALHOSTINPKTS		2
       #define COLUMN_ALHOSTOUTPKTS		3
       #define COLUMN_ALHOSTINOCTETS		4
       #define COLUMN_ALHOSTOUTOCTETS		5
       #define COLUMN_ALHOSTCREATETIME		6

/* column number definitions for table alMatrixSDTable */
       #define COLUMN_ALMATRIXSDTIMEMARK		1
       #define COLUMN_ALMATRIXSDPKTS		2
       #define COLUMN_ALMATRIXSDOCTETS		3
       #define COLUMN_ALMATRIXSDCREATETIME		4

/* column number definitions for table alMatrixDSTable */
       #define COLUMN_ALMATRIXDSTIMEMARK		1
       #define COLUMN_ALMATRIXDSPKTS		2
       #define COLUMN_ALMATRIXDSOCTETS		3
       #define COLUMN_ALMATRIXDSCREATETIME		4

#endif /* RMONTABLE_H */
